"use client";

import { FormEvent, useState } from "react";
import type { AnalysisResult } from "@/lib/types";

const SAMPLE_JOB = `We are seeking a Software Engineer to build reliable customer-facing products. The role requires TypeScript, React, Next.js, Node.js, PostgreSQL, Docker, testing and GitHub Actions. You will design REST APIs, improve application performance, collaborate with an agile team and communicate technical trade-offs.`;

export default function Home() {
  const [jobDescription, setJobDescription] = useState(SAMPLE_JOB);
  const [resumeText, setResumeText] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [role, setRole] = useState("Software Engineer");
  const [seniority, setSeniority] = useState("Intermediate");
  const [source, setSource] = useState<string | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState<"generate" | "analyze" | null>(null);
  const [error, setError] = useState("");

  async function generateResume() {
    setLoading("generate"); setError(""); setResult(null);
    try {
      const response = await fetch("/api/generate", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ role, seniority })
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      setResumeText(data.text); setFile(null); setSource(data.source);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Generation failed.");
    } finally { setLoading(null); }
  }

  async function analyze(event: FormEvent) {
    event.preventDefault(); setLoading("analyze"); setError(""); setResult(null);
    try {
      const form = new FormData();
      form.set("jobDescription", jobDescription);
      form.set("resumeText", resumeText);
      if (file) form.set("resumeFile", file);
      const response = await fetch("/api/analyze", { method: "POST", body: form });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      setResult(data.analysis);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Analysis failed.");
    } finally { setLoading(null); }
  }

  return (
    <main>
      <header className="hero">
        <nav><span className="brand">Open Resume Lab</span><span className="nav-label">Foundation v0.1</span></nav>
        <div className="hero-copy">
          <p className="eyebrow">LOCAL-FIRST · EXPLAINABLE · OPEN SOURCE</p>
          <h1>Explore candidate fit<br /><em>without exposing real people.</em></h1>
          <p className="lede">Generate fictional resumes, compare them with a role, and inspect every reason behind the score. Files are processed in memory and never stored by this application.</p>
          <div className="trust"><span>✓ No paid API required</span><span>✓ Synthetic demo data</span><span>✓ Human review required</span></div>
        </div>
      </header>

      <form onSubmit={analyze} className="workspace">
        <section className="panel generator">
          <div className="section-heading"><div><span className="step">01</span><h2>Create test data</h2></div><span className="badge">Privacy-safe</span></div>
          <p>Generate an entirely fictional profile using free local AI or the built-in generator.</p>
          <div className="inline-fields">
            <label>Target role<input value={role} onChange={(e) => setRole(e.target.value)} /></label>
            <label>Level<select value={seniority} onChange={(e) => setSeniority(e.target.value)}><option>Entry-level</option><option>Intermediate</option><option>Senior</option></select></label>
          </div>
          <button type="button" className="secondary" onClick={generateResume} disabled={loading !== null}>{loading === "generate" ? "Generating…" : "Generate fictional resume"}</button>
          {source && <p className="status">Generated by {source === "ollama" ? "your local Ollama model" : "the built-in offline generator"}.</p>}
        </section>

        <section className="panel inputs">
          <div className="section-heading"><div><span className="step">02</span><h2>Add role and resume</h2></div></div>
          <label>Job description<textarea rows={8} value={jobDescription} onChange={(e) => setJobDescription(e.target.value)} /></label>
          <label>Resume text<textarea rows={13} value={resumeText} onChange={(e) => { setResumeText(e.target.value); setFile(null); }} placeholder="Generate a fictional resume above, paste text, or upload a file." /></label>
          <div className="upload-row">
            <label className="file-button">Upload PDF, DOCX or TXT<input type="file" accept=".pdf,.docx,.txt" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setResumeText(""); }} /></label>
            <span>{file ? file.name : "Maximum 5 MB · processed in memory"}</span>
          </div>
          <button className="primary" disabled={loading !== null}>{loading === "analyze" ? "Analysing…" : "Analyse match"}<span>→</span></button>
          {error && <div className="error" role="alert">{error}</div>}
        </section>
      </form>

      {result && <section className="results" aria-live="polite">
        <div className="result-title"><div><p className="eyebrow">EXPLAINABLE RESULT</p><h2>Match analysis</h2></div><div className="score"><strong>{result.overallScore}</strong><span>/100</span></div></div>
        <p className="disclaimer">{result.disclaimer}</p>
        <div className="skills-grid">
          <div><h3>Supported skills</h3><div className="chips matched">{result.matchedSkills.length ? result.matchedSkills.map((s) => <span key={s}>{s}</span>) : <small>None detected</small>}</div></div>
          <div><h3>Skills to verify</h3><div className="chips missing">{result.missingSkills.length ? result.missingSkills.map((s) => <span key={s}>{s}</span>) : <small>None detected</small>}</div></div>
        </div>
        <div className="criteria">
          {result.criteria.map((item) => <article key={item.criterion}>
            <div className="criterion-top"><h3>{item.criterion}</h3><strong>{item.score}/100</strong></div>
            <div className="bar"><i style={{ width: `${item.score}%` }} /></div>
            <p>{item.explanation} <small>Weight: {item.weight}%</small></p>
            {item.evidence.length > 0 && <ul>{item.evidence.map((line, index) => <li key={index}>{line}</li>)}</ul>}
          </article>)}
        </div>
        <div className="bottom-grid">
          <div><h3>Fair interview prompts</h3><ol>{result.interviewQuestions.map((q) => <li key={q}>{q}</li>)}</ol></div>
          <div className="warnings"><h3>Review notes</h3><ul>{result.warnings.map((w) => <li key={w}>{w}</li>)}</ul></div>
        </div>
      </section>}

      <footer><span>Open Resume Lab</span><p>Built for learning—not automated employment decisions.</p></footer>
    </main>
  );
}
